import { columns } from '@/components/repayments/AllRepaymentsColumns';
import { AllRepaymentsDataTable } from '@/components/repayments/AllRepaymentsDataTable';
import { Repayment } from '@/types';

export default async function AllRepaymentsPage() {
  const allRepayments: Repayment[] = [
    {
      repaymentId: 1,
      loanNumber: 'LN-2024-001',
      repaymentNumber: '1',
      principalAmount: 45000,
      interestAmount: 5000,
      lateFee: 0,
      amount: 50000,
      outstandingAmount: 0,
      amountPaid: 50000,
      dueDate: '2024-02-15',
      repaymentDate: '2024-02-14',
      createDate: '2024-01-15',
      status: 'Paid',
      repaymentChannel: 'Direct Debit',
      loan: {
        id: 1,
        loanId: 1,
        loanNumber: 'LN-2024-001',
        currency: 'NGN',
        amount: 500000,
        amountPaid: 50000,
        customerID: 'CUST-001',
        customerName: 'John Adebayo',
        phoneNumber: '08012345678',
        email: 'john.adebayo@email.com',
        interestRate: 12,
        interest: 60000,
        lateFee: 0,
        duration: 12,
        maturityDate: '2025-01-15',
        loanBalance: 450000,
        totalRepaymentAmount: 560000,
        installmentAmount: 46667,
        status: 'Active',
        createDate: '2024-01-15',
        vendorName: 'PayLater Hub',
        vendorID: '1098',
        zohoInvoiceID: 'ZH-INV-001',
        zohoInvoiceNo: 'INV-001',
        zohoCustomerID: 'ZH-CUST-001',
        lastModified: '2024-01-15',
        createdBy: 'system',
        lastModifiedBy: 'system'
      },
      customer: {
        customerID: 'CUST-001',
        name: 'John Adebayo',
        firstName: 'John',
        lastName: 'Adebayo',
        email: 'john.adebayo@email.com',
        phoneNumber: '08012345678',
        gender: 'Male',
        dateOfBirth: '1990-05-15',
        maritalStatus: 'Single',
        customerStatus: 'Active',
        rmCode: 'RM001',
        address: '123 Lagos Street',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postalCode: '100001',
        landMark: 'Near Victoria Island',
        profilePicture: {
          pictureId: 1,
          filePath: '/docs/hju.png',
          fileName: 'profile.png',
          fileExtension: '.png',
          fileSize: 1024,
          contentType: 'image/png',
          picture: '',
          downloadUrl: '/docs/hju.png',
          lastModified: '2024-01-15'
        }
      }
    },
    {
      repaymentId: 2,
      loanNumber: 'LN-2024-002',
      repaymentNumber: '2',
      principalAmount: 70000,
      interestAmount: 5000,
      lateFee: 0,
      amount: 75000,
      outstandingAmount: 0,
      amountPaid: 75000,
      dueDate: '2024-03-15',
      repaymentDate: '2024-03-14',
      createDate: '2024-02-15',
      status: 'Paid',
      repaymentChannel: 'Bank Transfer',
      loan: {
        id: 2,
        loanId: 2,
        loanNumber: 'LN-2024-002',
        currency: 'NGN',
        amount: 750000,
        amountPaid: 75000,
        customerID: 'CUST-002',
        customerName: 'Sarah Okafor',
        phoneNumber: '08087654321',
        email: 'sarah.okafor@email.com',
        interestRate: 12,
        interest: 90000,
        lateFee: 0,
        duration: 10,
        maturityDate: '2024-12-15',
        loanBalance: 675000,
        totalRepaymentAmount: 840000,
        installmentAmount: 84000,
        status: 'Active',
        createDate: '2024-02-15',
        vendorName: 'PayLater Hub',
        vendorID: '1055',
        zohoInvoiceID: 'ZH-INV-002',
        zohoInvoiceNo: 'INV-002',
        zohoCustomerID: 'ZH-CUST-002',
        lastModified: '2024-02-15',
        createdBy: 'system',
        lastModifiedBy: 'system'
      },
      customer: {
        customerID: 'CUST-002',
        name: 'Sarah Okafor',
        firstName: 'Sarah',
        lastName: 'Okafor',
        email: 'sarah.okafor@email.com',
        phoneNumber: '08087654321',
        gender: 'Female',
        dateOfBirth: '1988-08-22',
        maritalStatus: 'Married',
        customerStatus: 'Active',
        rmCode: 'RM002',
        address: '456 Abuja Road',
        city: 'Abuja',
        state: 'FCT',
        country: 'Nigeria',
        postalCode: '900001',
        landMark: 'Near Central Area',
        profilePicture: {
          pictureId: 2,
          filePath: '/docs/hju.png',
          fileName: 'profile2.png',
          fileExtension: '.png',
          fileSize: 1024,
          contentType: 'image/png',
          picture: '',
          downloadUrl: '/docs/hju.png',
          lastModified: '2024-02-15'
        }
      }
    },
    {
      repaymentId: 3,
      loanNumber: 'LN-2024-003',
      repaymentNumber: '1',
      principalAmount: 25000,
      interestAmount: 3000,
      lateFee: 1000,
      amount: 29000,
      outstandingAmount: 5000,
      amountPaid: 24000,
      dueDate: '2024-01-30',
      repaymentDate: '2024-02-05',
      createDate: '2024-01-01',
      status: 'Partial',
      repaymentChannel: 'Mobile Money',
      loan: {
        id: 3,
        loanId: 3,
        loanNumber: 'LN-2024-003',
        currency: 'NGN',
        amount: 300000,
        amountPaid: 24000,
        customerID: 'CUST-003',
        customerName: 'Michael Eze',
        phoneNumber: '08098765432',
        email: 'michael.eze@email.com',
        interestRate: 15,
        interest: 45000,
        lateFee: 1000,
        duration: 6,
        maturityDate: '2024-07-01',
        loanBalance: 300000,
        totalRepaymentAmount: 345000,
        installmentAmount: 57500,
        status: 'Active',
        createDate: '2024-01-01',
        vendorName: 'PayLater Hub',
        vendorID: '1023',
        zohoInvoiceID: 'ZH-INV-003',
        zohoInvoiceNo: 'INV-003',
        zohoCustomerID: 'ZH-CUST-003',
        lastModified: '2024-01-01',
        createdBy: 'system',
        lastModifiedBy: 'system'
      },
      customer: {
        customerID: 'CUST-003',
        name: 'Michael Eze',
        firstName: 'Michael',
        lastName: 'Eze',
        email: 'michael.eze@email.com',
        phoneNumber: '08098765432',
        gender: 'Male',
        dateOfBirth: '1992-12-10',
        maritalStatus: 'Single',
        customerStatus: 'Active',
        rmCode: 'RM003',
        address: '789 Port Harcourt Street',
        city: 'Port Harcourt',
        state: 'Rivers',
        country: 'Nigeria',
        postalCode: '500001',
        landMark: 'Near GRA',
        profilePicture: {
          pictureId: 3,
          filePath: '/docs/hju.png',
          fileName: 'profile3.png',
          fileExtension: '.png',
          fileSize: 1024,
          contentType: 'image/png',
          picture: '',
          downloadUrl: '/docs/hju.png',
          lastModified: '2024-01-01'
        }
      }
    }
  ];

  return (
    <div className="2xl:px-2 mt-8">
      <AllRepaymentsDataTable
        columns={columns}
        data={allRepayments}
        columnFileName="AllRepaymentsColumns"
        emptyMessage="No repayments found."
      />
    </div>
  );
}
